import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Realistic Nanshan Kindergarten Data
  const schools = [
    {
      id: 'ns-01',
      name: '深圳市南山区机关幼儿园',
      type: '公立',
      address: '深圳市南山区南山大道1001号',
      district: '南山区',
      rating: 4.8,
      reviewCount: 128,
      coords: [22.5332, 113.9314],
      image: 'https://images.unsplash.com/photo-1595206133361-b1fe343e5e23?q=80&w=800&auto=format&fit=crop',
      subDistrict: '南山中心区',
      distance: '0.8km',
      description: '省级示范幼儿园，南山区历史最悠久的公办园之一。',
      features: ['省级示范', '师资雄厚', '口碑爆棚'],
      philosophy: '自然教育，快乐成长',
      philosophyTags: ['自然教育', '全面发展'],
      feeRange: 'RMB 1,000-1,500/月',
      status: '招生中',
    },
    {
      id: 'ns-02',
      name: '深圳大学附属幼儿园',
      type: '公立',
      address: '深圳市南山区南海大道3688号深圳大学内',
      district: '南山区',
      rating: 4.7,
      reviewCount: 92,
      coords: [22.5350, 113.9350],
      image: 'https://images.unsplash.com/photo-1588072432836-e10032774350?q=80&w=800&auto=format&fit=crop',
      subDistrict: '深大片区',
      distance: '1.2km',
      description: '依附深圳大学学术资源，教学氛围浓厚，环境极佳。',
      features: ['大学附属', '环境优美', '学术型'],
      philosophy: '润物无声，教学相长',
      philosophyTags: ['学术型', '全人教育'],
      feeRange: 'RMB 1,200-1,800/月',
      status: '即将截止',
    },
    {
      id: 'ns-03',
      name: '蛇口国际学校 (SIS) 幼儿园部',
      type: '国际',
      address: '深圳市南山区蛇口望海路1019号',
      district: '南山区',
      rating: 4.9,
      reviewCount: 65,
      coords: [22.4831, 113.9224],
      image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=800&auto=format&fit=crop',
      subDistrict: '蛇口',
      distance: '3.5km',
      description: '深圳历史最悠久的国际学校，IB课程体系，纯外教环境。',
      features: ['IB认证', '全英教学', '国际社区'],
      philosophy: '培养具有全球公民意识的学习者',
      philosophyTags: ['IB课程', '双语教学', '全人教育'],
      feeRange: 'RMB 18,000-25,000/月',
      status: '全年滚动',
    },
    {
      id: 'ns-04',
      name: '南山区教育科学研究院附属幼儿园',
      type: '公立',
      address: '深圳市南山区桃源街道办事处附近',
      district: '南山区',
      rating: 4.6,
      reviewCount: 45,
      coords: [22.5830, 113.9630],
      image: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=800&auto=format&fit=crop',
      description: '教研基地园，教学方法科学先进，注重儿童心理发展。',
      features: ['实验园', '科研领先', '桃源片区'],
      philosophy: '科学育儿，智慧成长',
      philosophyTags: ['科学育儿', '探究式'],
      feeRange: 'RMB 1,000-1,300/月',
      status: '资料审核中',
    },
    {
      id: 'ns-05',
      name: '蒙世学堂 (赤湾分园)',
      type: '私立',
      address: '深圳市南山区赤湾五路一号',
      district: '南山区',
      rating: 4.7,
      reviewCount: 38,
      coords: [22.4790, 113.9050],
      image: 'https://images.unsplash.com/photo-1603072899764-f8c443b3a6ef?q=80&w=800&auto=format&fit=crop',
      description: '深受家长好评的纯正蒙氏教育，混龄班级，环境整洁，关注个体细节。',
      features: ['纯正蒙氏', '混龄编班', '安静雅致'],
      philosophy: '追随孩子，助其自立。',
      philosophyTags: ['蒙特梭利'],
      feeRange: 'RMB 9,000-13,000/月',
      status: '有名额',
    },
    {
      id: 'ns-06',
      name: '蔚蓝海岸中心幼儿园',
      type: '私立',
      address: '深圳市南山区蔚蓝海岸社区内',
      district: '南山区',
      rating: 4.5,
      reviewCount: 110,
      coords: [22.5120, 113.9450],
      image: 'https://images.unsplash.com/photo-1592066409343-da53556f8f53?q=80&w=800&auto=format&fit=crop',
      description: '大型社区配套园，配套设施齐全，体育运动丰富。',
      features: ['大型操场', '英语特色', '社区便利'],
      philosophy: '健康、自信、快乐',
      philosophyTags: ['体育特色', '英语特色'],
      feeRange: 'RMB 4,000-6,000/月',
      status: '学位紧张',
    },
    {
      id: 'ns-07',
      name: '科苑幼儿园',
      type: '公立',
      address: '深圳市南山区科技园科苑南路',
      district: '南山区',
      rating: 4.6,
      reviewCount: 77,
      coords: [22.5340, 113.9510],
      image: 'https://images.unsplash.com/photo-1576269062838-89c0a6b7d56e?q=80&w=800&auto=format&fit=crop',
      description: '位于科技园核心区，家长素质高，科技与艺术融合教学。',
      features: ['科技园核心', '艺术特色', '家长委员会活跃'],
      philosophy: '启迪智慧，艺术生活',
      philosophyTags: ['艺术启蒙', '科技特色'],
      feeRange: 'RMB 1,100-1,400/月',
      status: '已报满',
    },
    {
      id: 'ft-01',
      name: '深圳市实验幼儿园',
      type: '公立',
      address: '深圳市福田区百花二路',
      district: '福田区',
      rating: 4.9,
      reviewCount: 210,
      coords: [22.5530, 114.0790],
      image: 'https://images.unsplash.com/photo-1564429234816-6419ca9175a1?q=80&w=800&auto=format&fit=crop',
      description: '百花片区顶流，实验教育集团旗下，教学质量全深领先。',
      features: ['百花学位', '名师云集', '高素质圈层'],
      philosophy: '办实验之园，育未来之星',
      philosophyTags: ['全面发展', '精英教育'],
      feeRange: 'RMB 1,200-1,600/月',
      status: '等候名单中',
    },
    {
      id: 'ba-01',
      name: '宝安区机关幼儿园',
      type: '公立',
      address: '深圳市宝安区新安街道',
      district: '宝安区',
      rating: 4.7,
      reviewCount: 156,
      coords: [22.5640, 113.9010],
      image: 'https://images.unsplash.com/photo-1502086223501-7ea244b0a4bb?q=80&w=800&auto=format&fit=crop',
      description: '宝安老牌公办园，占地广，设施全，师资稳定。',
      features: ['宝安龙头', '大场地', '生活化教学'],
      philosophy: '让每个孩子拥有彩色的童年',
      feeRange: 'RMB 1,000-1,500/月',
      status: '招生开启',
    },
    {
      id: 'lg-01',
      name: '龙岗区直属机关幼儿园',
      type: '公立',
      address: '深圳市龙岗区龙城街道',
      district: '龙岗区',
      rating: 4.6,
      reviewCount: 88,
      coords: [22.7180, 114.2450],
      image: 'https://images.unsplash.com/photo-1594608661623-aa0bd3a67d28?q=80&w=800&auto=format&fit=crop',
      description: '龙岗区标杆园所，环境优雅，注重多元文化培养。',
      features: ['龙岗中心', '特色绘本', '多元智能'],
      philosophy: '和谐发展，自然成长',
      feeRange: 'RMB 1,000-1,400/月',
      status: '咨询中',
    },
    {
      id: 'ns-08',
      name: '红树西岸幼儿园',
      type: '私立',
      address: '深圳市南山区白石洲',
      district: '南山区',
      rating: 3.8,
      reviewCount: 1,
      coords: [22.5280, 113.9450],
      image: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?q=80&w=800&auto=format&fit=crop',
      subDistrict: '白石洲',
      distance: '3.1km',
      description: '高端社区配套，面向白石洲高端住宅区，环境优越。',
      features: ['近地铁站', '白石洲', '设施现代'],
      philosophy: '接轨国际，快乐成长',
      feeRange: 'RMB 8,000-12,000/月',
      status: '资料递交中',
    },
    {
      id: 'ns-09',
      name: '海丽达·专业幼儿园升小学衔接',
      type: '私立',
      address: '深圳市南山区科技园',
      district: '南山区',
      rating: 4.8,
      reviewCount: 178,
      coords: [22.5450, 113.9550],
      image: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?q=80&w=800&auto=format&fit=crop',
      subDistrict: '科技园',
      distance: '4.7km',
      description: '专注于幼小衔接教育，课程体系完善，多年来深获家长好评。',
      features: ['幼小衔接', '科技园', '口碑极佳'],
      philosophy: '为小学生活做好全面准备',
      philosophyTags: ['幼小衔接', '全面发展'],
      feeRange: 'RMB 6,500-9,000/月',
      status: '有名额',
    },
    {
      id: 'ns-10',
      name: '深圳市育才教育集团第一幼儿园',
      type: '公立',
      address: '深圳市南山区蛇口商圈',
      district: '南山区',
      rating: 3.8,
      reviewCount: 6,
      coords: [22.4850, 113.9210],
      image: 'https://images.unsplash.com/photo-1562619371-b67725b6fde2?q=80&w=800&auto=format&fit=crop',
      subDistrict: '蛇口商圈',
      distance: '2.7km',
      description: '育才教育集团旗下老牌公立园，底蕴深厚，教研实力强。',
      features: ['蛇口商圈', '近地铁', '老牌名园'],
      philosophy: '育人为本，全面发展',
      feeRange: 'RMB 1,100-1,300/月',
      status: '学位锁定',
    },
    {
      id: 'ns-11',
      name: '深圳湾第一幼儿园',
      type: '公立',
      address: '深圳市南山区太古城',
      district: '南山区',
      rating: 4.5,
      reviewCount: 32,
      coords: [22.4980, 113.9420],
      image: 'https://images.unsplash.com/photo-1481833761820-0509d3217039?q=80&w=800&auto=format&fit=crop',
      subDistrict: '太古城',
      distance: '552m',
      description: '坐落于深圳湾核心区域，环境极具现代感，设施顶级。',
      features: ['太古城', '深圳湾', '政府直属'],
      philosophy: '拥抱未来，探索创新',
      feeRange: 'RMB 1,200-1,500/月',
      status: '审核中',
    },
    {
      id: 'ns-12',
      name: '蔚蓝海岸东区幼儿园',
      type: '私立',
      address: '深圳市南山区海岸城/保利',
      district: '南山区',
      rating: 4.0,
      reviewCount: 15,
      coords: [22.5180, 113.9380],
      image: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?q=80&w=800&auto=format&fit=crop',
      subDistrict: '海岸城/保利',
      distance: '958m',
      description: '海岸城片区优质社区园，注重户外运动，师生关系融洽。',
      features: ['近地铁', '社区配套', '亲近自然'],
      philosophy: '阳光、健康、向上',
      feeRange: 'RMB 4,500-6,500/月',
      status: '学位紧张',
    },
    {
      id: 'ns-13',
      name: '深圳市南山区科技第二幼儿园',
      type: '公立',
      address: '深圳市南山区科技园',
      district: '南山区',
      rating: 3.8,
      reviewCount: 2,
      coords: [22.5400, 113.9600],
      image: 'https://images.unsplash.com/photo-1540479859555-17af45c78602?q=80&w=800&auto=format&fit=crop',
      subDistrict: '科技园',
      distance: '2.6km',
      description: '科技园片区重点建设公办园，硬件设施一流，教研活跃。',
      features: ['科技园', '大操场', '双语环境'],
      philosophy: '创设适合每个儿童发展的环境',
      feeRange: 'RMB 1,100-1,400/月',
      status: '招生开启',
    },
    {
      id: 'ns-14',
      name: '北京师范大学蔚蓝海岸南区幼儿园',
      type: '私立',
      address: '深圳市南山区南油',
      district: '南山区',
      rating: 4.2,
      reviewCount: 45,
      coords: [22.5080, 113.9320],
      image: 'https://images.unsplash.com/photo-1473649085228-583485ff7b8d?q=80&w=800&auto=format&fit=crop',
      description: '北师大品牌授权，共享优质教育资源，学术指导力强。',
      features: ['南油片区', '北师大背景', '名校联盟'],
      philosophy: '学为人师，行为世范',
      feeRange: 'RMB 5,500-8,000/月',
      status: '有名额',
    },
    {
      id: 'ns-15',
      name: '西海湾花园幼儿园',
      type: '私立',
      address: '深圳市南山区南油',
      district: '南山区',
      rating: 3.8,
      reviewCount: 3,
      coords: [22.5050, 113.9280],
      image: 'https://images.unsplash.com/photo-1511216335778-7cb8f49fa7a3?q=80&w=800&auto=format&fit=crop',
      description: '社区精品园，环境温馨，注重日常习惯养成。',
      features: ['南油', '花园社区', '小班授课'],
      philosophy: '在生活中学习，在快乐中成长',
      feeRange: 'RMB 3,800-5,500/月',
      status: '咨询中',
    },
    {
      id: 'ns-16',
      name: '康乐幼儿园',
      type: '公立',
      address: '深圳市南山区蛇口商圈',
      district: '南山区',
      rating: 3.5,
      reviewCount: 1,
      coords: [22.4820, 113.9180],
      image: 'https://images.unsplash.com/photo-1597484661643-2f5fc9c88b74?q=80&w=800&auto=format&fit=crop',
      description: '蛇口片区普惠性公办园，性价比极高，服务周边居民多年。',
      features: ['蛇口', '高性价比', '普惠园'],
      philosophy: '健康第一，快乐为伴',
      feeRange: 'RMB 900-1,200/月',
      status: '学位紧张',
    },
    {
      id: 'ns-17',
      name: '童年幼儿园 (华明路)',
      type: '私立',
      address: '深圳市南山区南油',
      district: '南山区',
      rating: 3.4,
      reviewCount: 2,
      coords: [22.5020, 113.9350],
      image: 'https://images.unsplash.com/photo-1495147466023-ac5c588e2e94?q=80&w=800&auto=format&fit=crop',
      description: '温馨的成长家园，老师耐心负责，环境充满童趣。',
      features: ['南油', '老师亲切', '温馨环境'],
      philosophy: '留住最纯真的童年',
      feeRange: 'RMB 3,500-5,000/月',
      status: '招生中',
    },
    {
      id: 'ns-18',
      name: '澳城花园幼儿园',
      type: '私立',
      address: '深圳市南山区蛇口商圈',
      district: '南山区',
      rating: 3.7,
      reviewCount: 4,
      coords: [22.4880, 113.9250],
      image: 'https://images.unsplash.com/photo-1527847263472-aa5338d178b8?q=80&w=800&auto=format&fit=crop',
      description: '坐落于澳城花园，管理规范，重视家园共育。',
      features: ['蛇口', '家园共育', '规范化管理'],
      philosophy: '爱在起点，赢在未来',
      feeRange: 'RMB 4,200-6,000/月',
      status: '有名额',
    },
    {
      id: 'ns-19',
      name: '维多利亚幼儿园 (丽林校区)',
      type: '私立',
      address: '深圳市南山区中心区',
      district: '南山区',
      rating: 3.7,
      reviewCount: 8,
      coords: [22.5250, 113.9380],
      image: 'https://images.unsplash.com/photo-1502621003444-239474775d04?q=80&w=800&auto=format&fit=crop',
      description: '维多利亚品牌分校，国际视野，注重品格教育。',
      features: ['名牌连锁', '品格教育', '国际化'],
      philosophy: '培养具有国际情怀的世界公民',
      feeRange: 'RMB 12,000-16,000/月',
      status: '审核中',
    },
    {
      id: 'ns-20',
      name: '佳嘉豪苑幼儿园',
      type: '私立',
      address: '深圳市南山区中心区',
      district: '南山区',
      rating: 3.9,
      reviewCount: 4,
      coords: [22.5200, 113.9420],
      image: 'https://images.unsplash.com/photo-1522661060204-8b1d227b72ae?q=80&w=800&auto=format&fit=crop',
      description: '交通便利，园舍虽然紧凑但利用合理，活动丰富。',
      features: ['近地铁', '中心区', '活动丰富'],
      philosophy: '在活动中学习',
      feeRange: 'RMB 4,000-5,500/月',
      status: '有名额',
    },
    {
      id: 'ns-21',
      name: '深圳市南山区花园城三期幼儿园',
      type: '私立',
      address: '深圳市南山区蛇口商圈',
      district: '南山区',
      rating: 3.8,
      reviewCount: 3,
      coords: [22.4900, 113.9200],
      image: 'https://images.unsplash.com/photo-1560416313-414b33c856a9?q=80&w=800&auto=format&fit=crop',
      description: '成熟社区园所，服务花园城片区居民，安全保障好。',
      features: ['蛇口', '安全保障', '成熟社区'],
      philosophy: '安全第一，呵护成长',
      feeRange: 'RMB 4,500-6,000/月',
      status: '锁定中',
    },
    {
      id: 'ns-22',
      name: '荟同幼儿园',
      type: '国际',
      address: '深圳市南山区前海',
      district: '南山区',
      rating: 4.5,
      reviewCount: 30,
      coords: [22.5350, 113.9050],
      image: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?q=80&w=800&auto=format&fit=crop',
      description: '全球视野下的中国学校，前海标杆国际化园所。',
      features: ['前海', '国际化视野', '高端设施'],
      philosophy: '为大问题寻找答案',
      philosophyTags: ['PBL项目制', '创新型', '双语教学'],
      feeRange: 'RMB 20,000-28,000/月',
      status: '有名额',
    },
    {
      id: 'ns-23',
      name: '海印长城儿童学苑',
      type: '私立',
      address: '深圳市南山区中心区',
      district: '南山区',
      rating: 3.9,
      reviewCount: 4,
      coords: [22.5180, 113.9480],
      image: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?q=80&w=800&auto=format&fit=crop',
      description: '专注儿童全面素质培养，环境优雅，特色课程多。',
      features: ['中心区', '近地铁', '素质教育'],
      philosophy: '点亮孩子的未来',
      feeRange: 'RMB 6,000-8,500/月',
      status: '资料递交中',
    },
    {
      id: 'ns-24',
      name: '湾厦幼儿园',
      type: '公立',
      address: '深圳市南山区蛇口商圈',
      district: '南山区',
      rating: 3.5,
      reviewCount: 8,
      coords: [22.4850, 113.9350],
      image: 'https://images.unsplash.com/photo-1594608661623-aa0bd3a67d28?q=80&w=800&auto=format&fit=crop',
      description: '深耕湾厦社区，服务意识强，教学扎实。',
      features: ['蛇口', '湾厦', '老牌园所'],
      philosophy: '朴实、扎实、真实',
      feeRange: 'RMB 1,000-1,200/月',
      status: '学位紧张',
    },
    {
      id: 'ns-25',
      name: '深圳市南山区淇乐幼儿园',
      type: '私立',
      address: '深圳市南山区花园城',
      district: '南山区',
      rating: 3.9,
      reviewCount: 7,
      coords: [22.4950, 113.9250],
      image: 'https://images.unsplash.com/photo-1564429234816-6419ca9175a1?q=80&w=800&auto=format&fit=crop',
      description: '理念新颖，注重美育与艺术表达。',
      features: ['花园城', '美育特色', '师生互动好'],
      philosophy: '在美中发现，在爱中成长',
      feeRange: 'RMB 5,000-7,000/月',
      status: '咨询中',
    },
    {
      id: 'ns-26',
      name: '深圳市育才教育集团第三幼儿园',
      type: '公立',
      address: '深圳市南山区蛇口商圈',
      district: '南山区',
      rating: 3.9,
      reviewCount: 7,
      coords: [22.4800, 113.9220],
      image: 'https://images.unsplash.com/photo-1511216335778-7cb8f49fa7a3?q=80&w=800&auto=format&fit=crop',
      description: '育才集团分部，教学资源共享，管理严谨。',
      features: ['育才系', '蛇口', '公办精品'],
      philosophy: '全面育人，特长发展',
      feeRange: 'RMB 1,100-1,400/月',
      status: '即将报满',
    },
    {
      id: 'ns-27',
      name: '鲸湾幼儿园 The Bay School',
      type: '私立',
      address: '深圳市南山区蛇口商圈',
      district: '南山区',
      rating: 4.7,
      reviewCount: 63,
      coords: [22.4750, 113.9150],
      image: 'https://images.unsplash.com/photo-1502621003444-239474775d04?q=80&w=800&auto=format&fit=crop',
      description: '高关注度园所，不仅设施先进，更注重国际教育理念的落地。',
      features: ['高端私立', '有名额', '蛇口片区'],
      philosophy: '扎根中华，放眼世界',
      feeRange: 'RMB 15,000-22,000/月',
      status: '学位开放',
    },
    {
      id: 'ns-28',
      name: '南油第一幼儿园',
      type: '公立',
      address: '深圳市南山区南油',
      district: '南山区',
      rating: 3.4,
      reviewCount: 2,
      coords: [22.5050, 113.9350],
      image: 'https://images.unsplash.com/photo-1473649085228-583485ff7b8d?q=80&w=800&auto=format&fit=crop',
      description: '历史悠久的公立园，为周边居民提供稳定优质的基础教育。',
      features: ['南油', '稳定师资', '公益性强'],
      philosophy: '诚信办学，爱心育人',
      feeRange: 'RMB 1,000-1,300/月',
      status: '审核结束',
    },
    {
      id: 'ns-29',
      name: '滨海之窗花园幼儿园',
      type: '私立',
      address: '深圳市南山区南山中心区',
      district: '南山区',
      rating: 3.6,
      reviewCount: 10,
      coords: [22.5200, 113.9500],
      image: 'https://images.unsplash.com/photo-1588072432836-e10032774350?q=80&w=800&auto=format&fit=crop',
      description: '海景社区园所，空气清新，活动场地开阔。',
      features: ['海景视野', '中心区', '设施完备'],
      philosophy: '胸怀大海，志存高远',
      feeRange: 'RMB 5,500-7,500/月',
      status: '有名额',
    },
    {
      id: 'ns-30',
      name: 'ICDC国际儿童成长中心',
      type: '国际',
      address: '深圳市南山区花园城',
      district: '南山区',
      rating: 4.4,
      reviewCount: 32,
      coords: [22.4920, 113.9280],
      image: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?q=80&w=800&auto=format&fit=crop',
      description: '不仅是幼儿园，更是综合性成长中心，项目制教学深受好评。',
      features: ['PBL教学', '花园城', '深度关注'],
      philosophy: '探索、创造、成长',
      philosophyTags: ['探究式', '艺术启蒙'],
      feeRange: 'RMB 14,000-20,000/月',
      status: '滚动招生',
    },
    {
      id: 'ns-31',
      name: '卓英国际幼儿学院 Joying International',
      type: '国际',
      address: '深圳市南山区蛇口商圈',
      district: '南山区',
      rating: 4.6,
      reviewCount: 41,
      coords: [22.4800, 113.9100],
      image: 'https://images.unsplash.com/photo-1595206133361-b1fe343e5e23?q=80&w=800&auto=format&fit=crop',
      description: '纯正国际学院风，优秀的师资团队，关注社交情感发展。',
      features: ['蛇口', '国际学院', '菁英圈层'],
      philosophy: '卓越始于幼年',
      feeRange: 'RMB 16,000-24,000/月',
      status: '咨询中',
    }

  ];

  // API Routes
  app.get("/api/schools", (req, res) => {
    res.json(schools);
  });

  const notes = [
    {
      id: 'n1',
      title: '南山区机关幼儿园真实体验：面试流程全记录',
      author: '皮皮妈',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Pipi',
      schoolName: '南山区机关幼儿园',
      schoolId: 'ns-01',
      image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=400&auto=format&fit=crop',
      likes: 124,
      tags: ['面试经验', '公立园']
    },
    {
      id: 'n2',
      title: '国际园怎么选？蛇口SIS vs 深外国际真实对比',
      author: 'Kevin Dad',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kevin',
      schoolName: '蛇口国际学校',
      schoolId: 'ns-03',
      image: 'https://images.unsplash.com/photo-1595206133361-b1fe343e5e23?q=80&w=400&auto=format&fit=crop',
      likes: 89,
      tags: ['择校攻略', '国际化']
    },
    {
      id: 'n3',
      title: '蒙氏教育到底值不值？在蒙世学堂的这一年',
      author: '安安妈妈',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Anan',
      schoolName: '蒙世学堂',
      schoolId: 'ns-05',
      image: 'https://images.unsplash.com/photo-1620912189865-1e8a33da4c5e?q=80&w=400&auto=format&fit=crop',
      likes: 256,
      tags: ['避雷指南', '蒙特梭利']
    },
    {
      id: 'n4',
      title: '工薪家庭在南山如何低成本选择优质幼儿园',
      author: '大桥',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Daqiao',
      schoolName: '蔚蓝海岸中心幼儿园',
      schoolId: 'ns-06',
      image: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=400&auto=format&fit=crop',
      likes: 412,
      tags: ['省钱攻略', '普惠园']
    }
  ];

  app.get("/api/notes", (req, res) => {
    res.json(notes);
  });

  app.get("/api/schools/:id", (req, res) => {
    const school = schools.find(s => s.id === req.params.id);
    if (school) {
      // Multiple sets of reviews to choose from based on school ID
      const reviewPools = [
        [
          {
            id: 'r1',
            author: '王妈妈',
            avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Wang',
            rating: 5,
            date: '2024-05-01',
            content: '这里的老师真的很专业，孩子从刚开始的哭闹到现在的期待，进步很大。环境也非常整洁，每天都有消毒记录，非常放心。',
            tags: ['老师好', '环境整洁', '消毒到位']
          },
          {
            id: 'r2',
            author: 'Li Family',
            avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Li',
            rating: 4,
            date: '2024-04-12',
            content: '设施很全，但是报名人真的太多了，排队很久。不过课程设置很有趣味性，孩子回来经常分享学到的新知识。',
            tags: ['竞争大', '名校', '课程有趣']
          }
        ],
        [
          {
            id: 'r3',
            author: '陈大大',
            avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chen',
            rating: 5,
            date: '2024-03-22',
            content: '非常棒的园所！伙食特别好，每天菜谱都不重样，孩子都吃胖了。而且户外活动时间充足，老师很有耐心。',
            tags: ['伙食好', '户外多', '老师耐心']
          },
          {
            id: 'r4',
            author: '张小妈',
            avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Zhang',
            rating: 4,
            date: '2024-02-15',
            content: '校车线路很全面，基本上南山区大部分地区都能覆盖到。园舍虽然不算大，但布置得很有童趣，氛围很好。',
            tags: ['交通便利', '氛围温馨', '校车覆盖']
          }
        ]
      ];
      
      // Select pool based on string char code sum
      const poolIndex = req.params.id.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0) % reviewPools.length;

      res.json({
        ...school,
        reviews: reviewPools[poolIndex]
      });
    } else {
      res.status(404).json({ message: "School not found" });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
